# Executes a build of the demo-project on jenkins running inside a docker container
# The build runs inside a manually started and registered agent-container

name: manually started agent

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ setupBuildOnManuallyStartedAgent ]
  pull_request:
    branches: [ setupBuildOnManuallyStartedAgent ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches: [ setupBuildOnManuallyStartedAgent ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job starts a Jenkins server running inside a Docker container and builds the testproject
  buildOnManuallyStartedAgent:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
       matrix:
          java: [ 1.8 ]
       fail-fast: false

    defaults:
      run:
        working-directory: buildOnManuallyStartedAgent

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
#    - name: Build peass and peass-ci
#      run: ../common/scripts/buildPeassAndPeassCI.sh
    - name: Build and run container
      run: ./buildOnManuallyStartedAgent.sh
    - name: Wait for jenkins startup
      run: ./waitForJenkinsStartup.sh
    - name: Register agent to controller
      run: ./registerAgentToController.sh
    - name: Wait for build end
      run: ./waitForBuildEnd.sh
#    - name: Check results
#      run: ./checkResults.sh
