# This is a basic workflow to help you get started with Actions

name: Build on agent started by jenkins

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job starts a Jenkins server running inside a Docker container and builds the testproject
  buildOnJenkinsStartedAgent:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
       matrix:
          java: [ 1.8, 11, 15 ]
       fail-fast: false

    defaults:
      run:
        working-directory: buildOnJenkinsStartedAgent

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build peass and peass-ci
      run: ../common/scripts/buildPeassAndPeassCI.sh
    - name: Build and run container
      run: ./buildOnJenkinsStartedAgent.sh
    - name: Wait for jenkins startup
      run: ./waitForJenkinsStartup.sh
    - name: Wait for build end
      run: ./waitForBuildEnd.sh
    - name: Check results
      run: ./checkResults.sh
